--- === ClipboardTool ===
---
--- Keep a history of the clipboard for text entries and manage the entries with a context menu
---
--- Originally based on TextClipboardHistory.spoon by Diego Zamboni with additional functions provided by a context menu
--- and on [code by VFS](https://github.com/VFS/.hammerspoon/blob/master/tools/clipboard.lua), but with many changes and some contributions and inspiration from [asmagill](https://github.com/asmagill/hammerspoon-config/blob/master/utils/_menus/newClipper.lua).
---
--- Download: [https://github.com/Hammerspoon/Spoons/raw/master/Spoons/ClipboardTool.spoon.zip](https://github.com/Hammerspoon/Spoons/raw/master/Spoons/ClipboardTool.spoon.zip)

local obj                    = {}
obj.__index                  = obj

-- Metadata
obj.name                     = "ClipboardTool"
obj.version                  = "0.7"
obj.author                   = "Alfred Schilken <alfred@schilken.de>"
obj.homepage                 = "https://github.com/Hammerspoon/Spoons"
obj.license                  = "MIT - https://opensource.org/licenses/MIT"

local getSetting             = function(label, default) return hs.settings.get(obj.name .. "." .. label) or default end
local setSetting             = function(label, value)
   hs.settings.set(obj.name .. "." .. label, value); return value
end

--- ClipboardTool.frequency
--- Variable
--- Speed in seconds to check for clipboard changes. If you check too frequently, you will degrade performance, if you check sparsely you will loose copies. Defaults to 0.8.
obj.frequency                = 0.8

--- ClipboardTool.hist_size
--- Variable
--- How many items to keep on history. Defaults to 100
obj.hist_size                = 100

--- ClipboardTool.max_entry_size
--- Variable
--- maximum size of a text entry
obj.max_entry_size           = 4990

--- ClipboardTool.max_size
--- Variable
--- Whether to check the maximum size of an entry. Defaults to `false`.
obj.max_size                 = getSetting('max_size', false)

--- ClipboardTool.show_copied_alert
--- Variable
--- If `true`, show an alert when a new item is added to the history, i.e. has been copied.
obj.show_copied_alert        = true

--- ClipboardTool.honor_ignoredidentifiers
--- Variable
--- If `true`, check the data identifiers set in the pasteboard and ignore entries which match those listed in `ClipboardTool.ignoredIdentifiers`. The list of identifiers comes from http://nspasteboard.org. Defaults to `true`
obj.honor_ignoredidentifiers = true

--- ClipboardTool.paste_on_select
--- Variable
--- Whether to auto-type the item when selecting it from the menu. Can be toggled on the fly from the chooser. Defaults to `false`.
obj.paste_on_select          = getSetting('paste_on_select', false)

--- ClipboardTool.logger
--- Variable
--- Logger object used within the Spoon. Can be accessed to set the default log level for the messages coming from the Spoon.
obj.logger                   = hs.logger.new('ClipboardTool')

--- ClipboardTool.ignoredIdentifiers
--- Variable
--- Types of clipboard entries to ignore, see http://nspasteboard.org. Code from https://github.com/asmagill/hammerspoon-config/blob/master/utils/_menus/newClipper.lua.
---
--- Notes:
---  * Default value (don't modify unless you know what you are doing):
--- ```
---  {
---     ["de.petermaurer.TransientPasteboardType"] = true, -- Transient : Textpander, TextExpander, Butler
---     ["com.typeit4me.clipping"]                 = true, -- Transient : TypeIt4Me
---     ["Pasteboard generator type"]              = true, -- Transient : Typinator
---     ["com.agilebits.onepassword"]              = true, -- Confidential : 1Password
---     ["org.nspasteboard.TransientType"]         = true, -- Universal, Transient
---     ["org.nspasteboard.ConcealedType"]         = true, -- Universal, Concealed
---     ["org.nspasteboard.AutoGeneratedType"]     = true, -- Universal, Automatic
---  }
--- ```
obj.ignoredIdentifiers       = {
   ["de.petermaurer.TransientPasteboardType"] = true, -- Transient : Textpander, TextExpander, Butler
   ["com.typeit4me.clipping"]                 = true, -- Transient : TypeIt4Me
   ["Pasteboard generator type"]              = true, -- Transient : Typinator
   ["com.agilebits.onepassword"]              = true, -- Confidential : 1Password
   ["org.nspasteboard.TransientType"]         = true, -- Universal, Transient
   ["org.nspasteboard.ConcealedType"]         = true, -- Universal, Concealed
   ["org.nspasteboard.AutoGeneratedType"]     = true, -- Universal, Automatic
}

--- ClipboardTool.deduplicate
--- Variable
--- Whether to remove duplicates from the list, keeping only the latest one. Defaults to `true`.
obj.deduplicate              = true

--- ClipboardTool.show_in_menubar
--- Variable
--- Whether to show a menubar item to open the clipboard history. Defaults to `true`
obj.show_in_menubar          = true

--- ClipboardTool.menubar_title
--- Variable
--- Fallback string to show in the menubar if no icon can be loaded. Defaults to `"\u{1f4cb}"`, which is the [Unicode clipboard character](https://codepoints.net/U+1F4CB)
obj.menubar_title            = "\u{1f4cb}"

--- ClipboardTool.use_system_menubar_icon
--- Variable
--- Whether to prefer a system icon in menubar (with automatic light/dark rendering). Defaults to `true`.
obj.use_system_menubar_icon  = getSetting('use_system_menubar_icon', true)

--- ClipboardTool.menubar_icon_light
--- Variable
--- Preferred system icon/SF Symbol name for light mode. Defaults to `"clipboard"`.
obj.menubar_icon_light       = getSetting('menubar_icon_light', 'clipboard')

--- ClipboardTool.menubar_icon_dark
--- Variable
--- Preferred system icon/SF Symbol name for dark mode. Defaults to `"clipboard.fill"`.
obj.menubar_icon_dark        = getSetting('menubar_icon_dark', 'clipboard.fill')

--- ClipboardTool.display_max_length
--- Variable
--- Number of characters to which each clipboard item will be truncated, when displaying in the menu. This only truncates in display, the full content will be used for searching and for pasting.
obj.display_max_length       = 200

--- ClipboardTool.prune_max_age_days
--- Variable
--- Maximum age (in days) for history entries. `0` disables age-based pruning.
---
--- Notes:
---  * Defaults to `0` (disabled, no behavior change)
obj.prune_max_age_days       = getSetting('prune_max_age_days', 0)

----------------------------------------------------------------------

-- Internal variable - Chooser/menu object
obj.selectorobj              = nil
-- Internal variable - Cache for focused window to work around the current window losing focus after the chooser comes up
obj.prevFocusedWindow        = nil
-- Internal variable - Timer object to look for pasteboard changes
obj.timer                    = nil

local pasteboard             = require("hs.pasteboard") -- http://www.hammerspoon.org/docs/hs.pasteboard.html
local hashfn                 = require("hs.hash").MD5

-- Keep track of last change counter
local last_change            = nil;
-- Array to store the clipboard history
local clipboard_history      = {}

-- Internal function - persist the current history so it survives across restarts
function _persistHistory()
   setSetting("items", clipboard_history)
end

local function _ageLabel(ts, now)
   if type(ts) ~= "number" then return nil end
   local delta = now - ts
   if delta < 0 then delta = 0 end
   if delta < 60 then
      return delta .. "s"
   elseif delta < 3600 then
      return math.floor(delta / 60) .. "m"
   elseif delta < 86400 then
      return math.floor(delta / 3600) .. "h"
   end
   return math.floor(delta / 86400) .. "d"
end

local function _utf8LengthOrBytes(s)
   local ok, len = pcall(utf8.len, s)
   if ok and len ~= nil then return len end
   return #s
end

local function _formatBytes(value)
   if type(value) ~= "number" then return nil end
   if value < 1024 then
      return value .. " byte"
   elseif value < 1024 * 1024 then
      return math.floor((value + 512) / 1024) .. "kb"
   end
   return string.format("%.1fmb", value / (1024 * 1024))
end

local function _estimateDataUrlBytes(data_url)
   if type(data_url) ~= "string" then return nil end
   local payload = data_url:match("^data:[^;]+;base64,(.+)$")
   if payload == nil then return #data_url end
   local padding = 0
   if payload:sub(-2) == "==" then
      padding = 2
   elseif payload:sub(-1) == "=" then
      padding = 1
   end
   return math.floor((#payload * 3) / 4) - padding
end

local function _firstTextFormat()
   local all_types = {}
   local ok_content, content_types = pcall(hs.pasteboard.contentTypes)
   if ok_content and type(content_types) == "table" then
      for _, t in ipairs(content_types) do table.insert(all_types, t:lower()) end
   end

   local ok_pb, pb_types = pcall(hs.pasteboard.pasteboardTypes)
   if ok_pb and type(pb_types) == "table" then
      for _, t in ipairs(pb_types) do table.insert(all_types, t:lower()) end
   end

   for _, t in ipairs(all_types) do
      if t:find("utf16", 1, true) ~= nil then return "utf-16" end
   end
   for _, t in ipairs(all_types) do
      if t:find("utf8", 1, true) ~= nil then return "utf-8" end
   end
   for _, t in ipairs(all_types) do
      if t:find("rtf", 1, true) ~= nil then return "rtf" end
   end
   for _, t in ipairs(all_types) do
      if t:find("html", 1, true) ~= nil then return "html" end
   end
   return nil
end

local function _lineBreakLabel(s)
   if type(s) ~= "string" then return nil end
   local has_crlf = s:find("\r\n", 1, true) ~= nil
   local has_lf = s:find("\n", 1, true) ~= nil
   local has_cr = s:find("\r", 1, true) ~= nil

   if has_crlf then return "newline CRLF" end
   if has_lf and has_cr then return "newline LF+CR" end
   if has_lf then return "newline LF" end
   if has_cr then return "newline CR" end
   return nil
end

local function _entrySubText(entry, now)
   local parts = {}
   local age = _ageLabel(entry.t, now)
   if age then table.insert(parts, "Age " .. age) end

   if entry.type == "image" then
      local image_bytes = entry.bytes or _estimateDataUrlBytes(entry.content)
      table.insert(parts, "image " .. (_formatBytes(image_bytes) or "n/a"))
   elseif entry.type == "text" then
      if type(entry.fmt) == "string" then
         local text_bytes = entry.bytes
         if type(text_bytes) ~= "number" and type(entry.content) == "string" then text_bytes = #entry.content end
         table.insert(parts, entry.fmt .. " " .. ((text_bytes and (text_bytes .. " byte")) or "n/a"))
      else
         local chars = entry.chars
         if type(chars) ~= "number" and type(entry.content) == "string" then chars = _utf8LengthOrBytes(entry.content) end
         table.insert(parts, "char " .. tostring(chars or 0))
      end

      local line_breaks = _lineBreakLabel(entry.content)
      if line_breaks then table.insert(parts, line_breaks) end
   end

   if #parts == 0 then return nil end
   return table.concat(parts, " — ")
end

local function _isDarkMode()
   return hs.host.interfaceStyle() == "Dark"
end

local function _imageFromNames(names)
   for _, name in ipairs(names) do
      if type(name) == "string" and name ~= "" then
         local ok, image = pcall(hs.image.imageFromName, name)
         if ok and image ~= nil then return image end
      end
   end
   return nil
end

function obj:_updateMenubarAppearance()
   if self.menubaritem == nil then return end

   if not self.use_system_menubar_icon then
      self.menubaritem:setIcon(nil)
      self.menubaritem:setTitle(self.menubar_title)
      return
   end

   local dark_mode = _isDarkMode()
   local primary = dark_mode and self.menubar_icon_dark or self.menubar_icon_light
   local secondary = dark_mode and self.menubar_icon_light or self.menubar_icon_dark
   local icon = _imageFromNames({
      primary,
      secondary,
      "clipboard",
      "clipboard.fill",
      "doc.on.clipboard",
      "doc.on.doc",
      "NSTouchBarComposeTemplate",
      "NSImageNameActionTemplate",
   })

   if icon ~= nil and self.menubaritem:setIcon(icon, true) ~= nil then
      self.menubaritem:setTitle(nil)
   else
      self.menubaritem:setIcon(nil)
      self.menubaritem:setTitle(self.menubar_title)
   end
end

--- ClipboardTool:onAppearanceChanged()
--- Method
--- Refresh menubar icon/title after an appearance change.
---
--- Parameters:
---  * None
function obj:onAppearanceChanged()
   self:_updateMenubarAppearance()
end

--- ClipboardTool:togglePasteOnSelect()
--- Method
--- Toggle the value of `ClipboardTool.paste_on_select`
---
--- Parameters:
---  * None
function obj:togglePasteOnSelect()
   self.paste_on_select = setSetting("paste_on_select", not self.paste_on_select)
   hs.notify.show("ClipboardTool", "Paste-on-select is now " .. (self.paste_on_select and "enabled" or "disabled"), "")
end

function obj:toggleMaxSize()
   self.max_size = setSetting("max_size", not self.max_size)
   hs.notify.show("ClipboardTool", "Max Size is now " .. (self.max_size and "enabled" or "disabled"), "")
end

-- Internal method - process the selected item from the chooser. An item may invoke special actions, defined in the `actions` variable.
function obj:_processSelectedItem(value)
   local actions = {
      none = function() end,
      clear = hs.fnutils.partial(self.clearAll, self),
      toggle_paste_on_select = hs.fnutils.partial(self.togglePasteOnSelect, self),
      toggle_max_size = hs.fnutils.partial(self.toggleMaxSize, self),
   }
   if self.prevFocusedWindow ~= nil then
      self.prevFocusedWindow:focus()
   end
   if value and type(value) == "table" then
      if value.action and actions[value.action] then
         actions[value.action](value)
      elseif value.text then
         if value.type == "text" then
            pasteboard.setContents(value.data)
         elseif value.type == "image" then
            pasteboard.writeObjects(hs.image.imageFromURL(value.data))
         end
         --         self:pasteboardToClipboard(value.text)
         local mods = hs.eventtap.checkKeyboardModifiers()
         local force_paste_on_select = (mods ~= nil and mods.shift == true)
         if (self.paste_on_select) or force_paste_on_select then
            hs.eventtap.keyStroke({ "cmd" }, "v")
         end
      end
      last_change = pasteboard.changeCount()
   end
end

--- ClipboardTool:clearAll()
--- Method
--- Clears the clipboard and history
---
--- Parameters:
---  * None
function obj:clearAll()
   pasteboard.clearContents()
   clipboard_history = {}
   _persistHistory()
   last_change = pasteboard.changeCount()
end

--- ClipboardTool:clearLastItem()
--- Method
--- Clears the last added to the history
---
--- Parameters:
---  * None
function obj:clearLastItem()
   table.remove(clipboard_history, 1)
   _persistHistory()
   last_change = pasteboard.changeCount()
end

-- Internal method: deduplicate the given list, and restrict it to the history size limit
function obj:dedupe_and_resize(list)
   local res = {}
   local hashes = {}
   local now = os.time()
   local max_age_days = tonumber(self.prune_max_age_days) or 0
   local pruning_enabled = max_age_days > 0
   local cutoff = pruning_enabled and (now - (max_age_days * 86400)) or nil

   for i, v in ipairs(list) do
      if #res < self.hist_size then
         -- Backward-compatible normalization (older entries may miss fields).
         if type(v) == "string" then
            v = { type = "text", content = v }
            if pruning_enabled then v.t = now end
         end

         if type(v) == "table" and type(v.content) == "string" then
            if v.type == nil then v.type = "text" end
            if pruning_enabled and type(v.t) ~= "number" then v.t = now end

            if (not pruning_enabled) or (v.t >= cutoff) then
               local hash = hashfn(v.content)
               if (not self.deduplicate) or (not hashes[hash]) then
                  table.insert(res, v)
                  hashes[hash] = true
               end
            end
         end
      end
   end
   return res
end

--- ClipboardTool:pasteboardToClipboard(item)
--- Method
--- Add the given string to the history
---
--- Parameters:
---  * item - string to add to the clipboard history
---  * meta - optional table with lightweight metadata (e.g. `fmt`, `bytes`, `chars`)
---
--- Returns:
---  * None
function obj:pasteboardToClipboard(item_type, item, meta)
   local entry = { type = item_type, content = item }
   if type(meta) == "table" then
      for k, v in pairs(meta) do
         entry[k] = v
      end
   end
   if (tonumber(self.prune_max_age_days) or 0) > 0 then entry.t = os.time() end
   table.insert(clipboard_history, 1, entry)
   clipboard_history = self:dedupe_and_resize(clipboard_history)
   _persistHistory() -- updates the saved history
end

-- Internal method: actions of the context menu, special paste
function obj:pasteAllWithDelimiter(row, delimiter)
   if self.prevFocusedWindow ~= nil then
      self.prevFocusedWindow:focus()
   end
   print("pasteAllWithTab row:" .. row)
   for ix = row, 1, -1 do
      local entry = clipboard_history[ix]
      print("pasteAllWithTab ix:" .. ix .. ":" .. entry)
      --      pasteboard.setContents(entry)
      --      os.execute("sleep 0.2")
      --      hs.eventtap.keyStroke({"cmd"}, "v")
      hs.eventtap.keyStrokes(entry.content)
      --      os.execute("sleep 0.2")
      hs.eventtap.keyStrokes(delimiter)
      --      os.execute("sleep 0.2")
   end
end

-- Internal method: actions of the context menu, delete or rearrange of clips
function obj:manageClip(row, action)
   print("manageClip row:" .. row .. ",action:" .. action)
   if action == 0 then
      table.remove(clipboard_history, row)
   elseif action == 2 then
      local i = 1
      local j = row
      while i < j do
         clipboard_history[i], clipboard_history[j] = clipboard_history[j], clipboard_history[i]
         i = i + 1
         j = j - 1
      end
   else
      local value = clipboard_history[row]
      local new = row + action
      if new < 1 then new = 1 end
      if new < row then
         table.move(clipboard_history, new, row - 1, new + 1)
      else
         table.move(clipboard_history, row + 1, new, row)
      end
      clipboard_history[new] = value
   end
   self.selectorobj:refreshChoicesCallback()
end

-- Internal method:
function obj:_showContextMenu(row)
   print("_showContextMenu row:" .. row)
   local point = hs.mouse.absolutePosition()
   local menu = hs.menubar.new(false)
   local menuTable = {
      { title = "Paste all with Tab",     fn = hs.fnutils.partial(self.pasteAllWithDelimiter, self, row, "\t") },
      { title = "Paste all with Newline", fn = hs.fnutils.partial(self.pasteAllWithDelimiter, self, row, "\n") },
      { title = "-" },
      { title = "Remove ",                fn = hs.fnutils.partial(self.manageClip, self, row, 0) },
      { title = "Move to top",            fn = hs.fnutils.partial(self.manageClip, self, row, -100) },
      { title = "Move up",                fn = hs.fnutils.partial(self.manageClip, self, row, -1) },
      { title = "Move down",              fn = hs.fnutils.partial(self.manageClip, self, row, 1) },
      { title = "Invert table",           fn = hs.fnutils.partial(self.manageClip, self, row, 2) },
      { title = "-" },
      { title = "disabled item",          disabled = true },
      { title = "checked item",           checked = true },
   }
   menu:setMenu(menuTable)
   menu:popupMenu(point)
   print(hs.inspect(point))
end

-- Internal function - fill in the chooser options, including the control options
function obj:_populateChooser(query)
   query = (query or ""):lower()
   local menuData = {}
   local now = os.time()
   for k, v in pairs(clipboard_history) do
      local sub_text = _entrySubText(v, now)
      if (v.type == "text" and (query == "" or v.content:lower():find(query))) then
         table.insert(menuData, {
            text = string.sub(v.content, 0, obj.display_max_length),
            subText = sub_text,
            data = v.content,
            type = v.type
         })
      elseif (v.type == "image") then
         table.insert(menuData, {
            text = "《Image data》",
            subText = sub_text,
            type = v.type,
            data = v.content,
            image = hs.image.imageFromURL(v.content)
         })
      end
   end
   if #menuData == 0 then
      table.insert(menuData, {
         text = "",
         subText = "《Clipboard is empty》",
         action = 'none',
         image = hs.image.imageFromName('NSCaution')
      })
   else
      table.insert(menuData, {
         text = "《Clear Clipboard History》",
         action = 'clear',
         image = hs.image.imageFromName('NSTrashFull')
      })
   end
   table.insert(menuData, {
      text = "《" .. (self.paste_on_select and "Disable" or "Enable") .. " Paste-on-select》",
      action = 'toggle_paste_on_select',
      image = (self.paste_on_select and hs.image.imageFromName('NSSwitchEnabledOn') or hs.image.imageFromName('NSSwitchEnabledOff'))
   })
   table.insert(menuData, {
      text = "《" .. (self.max_size and "Disable" or "Enable") .. " max size " .. self.max_entry_size .. "》",
      action = 'toggle_max_size',
      image = (self.max_size and hs.image.imageFromName('NSSwitchEnabledOn') or hs.image.imageFromName('NSSwitchEnabledOff'))
   })
   self.logger.df("Returning menuData = %s", hs.inspect(menuData))
   return menuData
end

--- ClipboardTool:shouldBeStored()
--- Method
--- Verify whether the pasteboard contents matches one of the values in `ClipboardTool.ignoredIdentifiers`
---
--- Parameters:
---  * None
function obj:shouldBeStored()
   -- Code from https://github.com/asmagill/hammerspoon-config/blob/master/utils/_menus/newClipper.lua
   local goAhead = true
   for i, v in ipairs(hs.pasteboard.pasteboardTypes()) do
      if self.ignoredIdentifiers[v] then
         goAhead = false
         break
      end
   end
   if goAhead then
      for i, v in ipairs(hs.pasteboard.contentTypes()) do
         if self.ignoredIdentifiers[v] then
            goAhead = false
            break
         end
      end
   end
   return goAhead
end

-- Internal method:
function obj:reduceSize(text)
   print(#text .. " ? " .. tostring(obj.max_entry_size))
   local endingpos = 3000
   local lastLowerPos = 3000
   local nextpos = nil
   repeat
      lastLowerPos = endingpos
      _, nextpos = string.find(text, "\n\n", endingpos + 1)
      if nextpos == nil then break end
      endingpos = nextpos
      print("endingpos:" .. endingpos)
   until endingpos > obj.max_entry_size
   return string.sub(text, 1, lastLowerPos)
end

--- ClipboardTool:checkAndStorePasteboard()
--- Method
--- If the pasteboard has changed, we add the current item to our history and update the counter
---
--- Parameters:
---  * None
function obj:checkAndStorePasteboard()
   local now = pasteboard.changeCount()
   if (now > last_change) then
      if (not self.honor_ignoredidentifiers) or self:shouldBeStored() then
         local current_clipboard = pasteboard.getContents()
         self.logger.df("current_clipboard = %s", tostring(current_clipboard))
         if (current_clipboard == nil) and (pasteboard.readImage() ~= nil) then
            current_clipboard = pasteboard.readImage()
            local image_data = current_clipboard:encodeAsURLString()
            self:pasteboardToClipboard("image", image_data, {
               bytes = _estimateDataUrlBytes(image_data)
            })
            if self.show_copied_alert then
               hs.alert.show("Copied image")
            end
            self.logger.df("Adding image (hashed) %s to clipboard history clipboard",
               hashfn(image_data))
         elseif current_clipboard ~= nil then
            local size = #current_clipboard
            if obj.max_size and size > obj.max_entry_size then
               local answer = hs.dialog.blockAlert("Clipboard",
                  "The maximum size of " .. obj.max_entry_size .. " was exceeded.", "Copy partially", "Copy all",
                  "NSCriticalAlertStyle")
               print("answer: " .. answer)
               if answer == "Copy partially" then
                  current_clipboard = self:reduceSize(current_clipboard)
                  size = #current_clipboard
               end
            end
            if self.show_copied_alert then
               hs.alert.show("Copied " .. size .. " chars")
            end
            self.logger.df("Adding %s to clipboard history", current_clipboard)
            self:pasteboardToClipboard("text", current_clipboard, {
               fmt = _firstTextFormat(),
               bytes = #current_clipboard,
               chars = _utf8LengthOrBytes(current_clipboard)
            })
         else
            self.logger.df("Ignoring nil clipboard content")
         end
      else
         self.logger.df("Ignoring pasteboard entry because it matches ignoredIdentifiers")
      end
      last_change = now
   end
end

--- ClipboardTool:start()
--- Method
--- Start the clipboard history collector
---
--- Parameters:
---  * None
function obj:start()
   obj.logger.level = 0
   clipboard_history = self:dedupe_and_resize(getSetting("items", {})) -- If no history is saved on the system, create an empty history
   if (tonumber(self.prune_max_age_days) or 0) > 0 then
      _persistHistory() -- persist normalized/pruned history once at startup
   end
   last_change = pasteboard.changeCount()                              -- keeps track of how many times the pasteboard owner has changed // Indicates a new copy has been made
   self.selectorobj = hs.chooser.new(hs.fnutils.partial(self._processSelectedItem, self))
   self.selectorobj:choices(hs.fnutils.partial(self._populateChooser, self, ""))
   self.selectorobj:queryChangedCallback(function(query)
      self.selectorobj:choices(hs.fnutils.partial(self._populateChooser, self, query))
   end)
   self.selectorobj:rightClickCallback(hs.fnutils.partial(self._showContextMenu, self))
   --Checks for changes on the pasteboard. Is it possible to replace with eventtap?
   self.timer = hs.timer.new(self.frequency, hs.fnutils.partial(self.checkAndStorePasteboard, self))
   self.timer:start()
   if self.show_in_menubar then
      self.menubaritem = hs.menubar.new()
          :setClickCallback(hs.fnutils.partial(self.toggleClipboard, self))
      self:_updateMenubarAppearance()
   end
end

--- ClipboardTool:showClipboard()
--- Method
--- Display the current clipboard list in a chooser
---
--- Parameters:
---  * None
function obj:showClipboard()
   if self.selectorobj ~= nil then
      self.selectorobj:refreshChoicesCallback()
      self.prevFocusedWindow = hs.window.focusedWindow()
      self.selectorobj:show()
   else
      hs.notify.show("ClipboardTool not properly initialized", "Did you call ClipboardTool:start()?", "")
   end
end

--- ClipboardTool:toggleClipboard()
--- Method
--- Show/hide the clipboard list, depending on its current state
---
--- Parameters:
---  * None
function obj:toggleClipboard()
   if self.selectorobj:isVisible() then
      self.selectorobj:hide()
   else
      self:showClipboard()
   end
end

--- ClipboardTool:bindHotkeys(mapping)
--- Method
--- Binds hotkeys for ClipboardTool
---
--- Parameters:
---  * mapping - A table containing hotkey objifier/key details for the following items:
---   * show_clipboard - Display the clipboard history chooser
---   * toggle_clipboard - Show/hide the clipboard history chooser
function obj:bindHotkeys(mapping)
   local def = {
      show_clipboard = hs.fnutils.partial(self.showClipboard, self),
      toggle_clipboard = hs.fnutils.partial(self.toggleClipboard, self),
   }
   hs.spoons.bindHotkeysToSpec(def, mapping)
   obj.mapping = mapping
end

return obj
